#ifndef WILDSCVKB_GLOBAL_H
#define WILDSCVKB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WILDSCVIRTUALKEYBOARD_LIBRARY)
#  define WILDSCVIRTUALKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WILDSCVIRTUALKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WILDSCVKB_GLOBAL_H
